#!/usr/bin/env bash
# a Bash script that will display information about subdomains.

print_info () {
     dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]; then
    print_info "$2.$1" "$2"
else
    subdomains=("www" "lb-01" "web-01" "web-02")
    domain="$1"
    
    for subdomain in "${subdomains[@]}"; do
        print_info "$subdomain.$domain" "$subdomain"
    done
fi
