#!/usr/bin/env bash
# Script to configure Nginx with a custom response header

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Set up directory and permissions
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www/html

# Create index and error pages
echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Update Nginx configuration with custom header
custom_header="X-Served-By"
sudo sed -i "s/add_header X-Served-By.*/add_header $custom_header \$hostname;/g" /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
