#!/usr/bin/env bash

# Backup and compress all databases
mysqldump --all-databases -u root --password="$1" > backup.sql

# Create a timestamp for the filename
timestamp=$(date +"%d-%m-%Y")

file_name="$timestamp.tar.gz"

# Compress the backup file
tar -czvf "$file_name" backup.sql
