#!/usr/bin/env bash
# bash script that manages "manage_my_process"


pid_file="/var/run/my_process.pid"

start_process()
{
    if [ -f "$pid_file" ]; then
        echo "manage_my_process is already running with
PID $(cat "$pid_file")"
    else
        ./manage_my_process &
        echo $! > "$pid_file"
        echo "manage_my_process started"
    fi
}
stop_process()
{
    if [ -f "$pid_file" ]; then
        pid=$(cat "$pid_file")
        kill "$pid"
        rm -f "$pid_file"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running"
    fi
}

restart_process()
{
    stop_process
    start_process
    echo "manage_my_process restarted"
}


case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac