#!/usr/bin/env bash
# bash script that manages "manage_my_process"



pid_file="/var/run/my_process.pid"

case "$1" in
    start)
        if [ -f "$pid_file" ]; then
            echo "manage_my_process is already running with
PID $(cat "$pid_file")"
        else
            manage_my_process &
            echo $! > "$pid_file"
            echo "manage_my_process started"
        fi
        ;;
    stop)
        if [ -f "$pid_file" ]; then
            echo "manage_my_process stopped"
            kill "$(cat "$pid_file")"
            rm "$pid_file"
        else
            echo "manage_my_process is not running"
        fi
        ;;
    restart)
        if [ -f "$pid_file" ]; then
            kill "$(cat "$pid_file")"
            rm "$pid_file"
        fi
        manage_my_process &
        echo $! > "$pid_file"
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
