#!/usr/bin/env bash
# Bash script that displays lines containing the bash word,
# thus allowing you to easily get the PID of your Bash process.
# shellcheck disable=SC2009

ps_output=$(ps auxf)

bash_lines=$(echo "$ps_output" | grep "bash")
echo "$bash_lines"
