#!/usr/bin/env bash
# a Bash script that displays To infinity and beyond indefinitely.
# Requirements: In between each iteration of the loop, add a sleep 2

counter=1
while true; do
    while [ $counter -le 5 ]; do
        echo "To infinity and beyond"
        sleep 2
        ((counter++))
    done
    counter=1
done