#!/usr/bin/env bash
#a Bash script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed

shopt -s nullglob
for i in *; do
  if [[ "$i" == *-* ]]; then
    name_after_dash="${i#*-}"
    echo "$name_after_dash"
  else
    echo "$i"
  fi
done
