#!/usr/bin/env bash
#a Bash script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed

mylist=$(ls | grep -v '^\.')

for i in $mylist; do
  echo "$i" | cut -d '-' -f2
done